Feature/premium page + stripe link
WildCodeSchool/2023-11-wns-bleu-g1 pull request #112
Opened 2024-07-09 14:52 UTC by AlexandreHamm

2024-07-12 03:38 UTC, Pouish85 requested changes

2024-07-12 03:38 UTC, Pouish85 commented on frontend/src/pages/premium.tsx
> +        {/* className="my-2 flex h-10 w-full items-center justify-center rounded-lg border border-neutral-500 text-base font-bold transition duration-100 hover:shadow-md hover:drop-shadow-md bg-neutr
Partie commentée à supprimer

2024-07-12 03:38 UTC, Pouish85 commented on frontend/src/pages/premium.tsx
> +            {/* <CheckCircledIcon className="h-6 w-6 text-green-500" /> */}
partie commentée à supprimée

2024-07-12 03:38 UTC, Pouish85 commented on frontend/src/components/elements/external-link-arrow.tsx
> +        <svg xmlns="http://www.w3.org/2000/svg" className="pl-2" height="70%" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" cla
className ?

2024-07-12 03:38 UTC, Pouish85 commented on frontend/src/pages/premium.tsx
> +            {option.external && <ExternalLinkIcon className="h-4 w-4 ml-2" />}
`className="h-4 w-4 ml-2"` non nécessaire

2024-07-12 03:38 UTC, Pouish85 commented on frontend/src/pages/premium.tsx
> +const PricingToggle = memo(
Question: pourquoi ne pas avoir utilisé le composant switch de shadcn?

2024-07-12 03:38 UTC, Pouish85 commented on frontend/src/pages/premium.tsx
> +const PricingCard = memo(({ option, enabled }: PricingCardProps) => (
Question: pourquoi ne pas avoir utilisé le composant card de shadcn?

2024-07-12 03:38 UTC, Pouish85 commented on frontend/src/pages/premium.tsx
> +        name: "Pro",
Le nom "Premium" n'est-il pas plus cohérent?

2024-07-12 06:53 UTC, Pouish85 requested changes
quelques petites modifications a effectuer

2024-07-12 06:53 UTC, Pouish85 commented on frontend/src/components/elements/auth-header.tsx
> +
```suggestion
```
ligne vide inutile

2024-07-12 06:53 UTC, Pouish85 commented on frontend/src/components/elements/external-link-arrow.tsx
> +        <svg xmlns="http://www.w3.org/2000/svg" className="pl-2" height="70%" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" cla
```suggestion
        <svg xmlns="http://www.w3.org/2000/svg" className="pl-2 lucide lucide-move-up-right" height="70%" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 5H19V11"/><path d="M19 5L5 19"/></svg>
```
Il faut utiliser className et non class, de plus tu avais déjà un champs className, j'ai juste déplacé tes classes CSS, vérifie si c'est bien le rendu que tu veux donner à ton élément

2024-07-12 06:53 UTC, Pouish85 commented on frontend/src/pages/premium.tsx
> +);
tu as des éléments déjà tout fait avec shadcn, tu devrais les utiliser car plus intégrés et allège le code

[switch](https://ui.shadcn.com/docs/components/switch)

2024-07-12 06:53 UTC, Pouish85 commented on frontend/src/pages/premium.tsx
> +));
tu as des éléments déjà tout fait avec shadcn, tu devrais les utiliser car plus intégrés et allège le code

[card](https://ui.shadcn.com/docs/components/card)

2024-07-12 12:45 UTC, AlexandreHamm reviewed
Should be good now

2024-08-27 09:30 UTC, AlexandreHamm commented
Tout doit être fix maintenant

2024-10-05 19:55 UTC, Pouish85 commented
Ne fonctionne pas chez moi conteneur remis a zéro, resetDb Lancé l'application tourne mais si je vais sur l'achat via mon abonnement, 9.99 payer j'ai un infinite loop
![image](https://github.com/user-attachments/assets/3e663545-2926-4fd5-87b7-f8359fc49f38)

2024-10-06 06:33 UTC, Pouish85 requested changes, later dismissed
Ne fonctionne pas chez moi conteneur remis a zéro, resetDb Lancé l'application tourne mais si avec compte flexmaster je vais sur l'achat via mon abonnement, 9.99 payer j'ai un infinite loop
￼

questions:

Est-ce que si l'utilisateur n'est pas abonné, dans le dropdown, est-ce normal qu'il y ai mon abonnement et pas passer premium?

Lors du désabonnement il doit manque r un refetch car avec compte test qui est premium je vais sur un projet, je peux le lancer indéfiniment, je me désabonne et je retourne sur le projet, je peux toujours le lancer indéfiniment, si je refresh la page, le compteur apparait. Le meme probleme apparait si je veux me réabonner, infinite loop

2024-10-07 09:10 UTC, AlexandreHamm commented
Pour la review, pensez bien aux variables d'environnement front & back (pour Stripe)

2024-10-07 10:38 UTC, ThomMarchand commented on backend/src/services/user.service.ts
> +		console.log("user", user);
console.log a delete

2024-10-07 10:38 UTC, ThomMarchand commented on frontend/src/components/elements/CheckoutPage.tsx
> +		// const cardElement = elements.getElement(PaymentElement);
commentaire à delete

2024-10-07 12:57 UTC, ThomMarchand commented on frontend/src/components/elements/CheckoutPage.tsx
supprime les import pas utilisé

2024-10-07 12:57 UTC, ThomMarchand commented on frontend/src/components/elements/CheckoutPage.tsx
> +	const form = useForm();
![image](https://github.com/user-attachments/assets/bcaf2ced-3372-47bb-b5dd-57c7f088e6bc)

2024-10-07 12:57 UTC, ThomMarchand commented on frontend/src/components/elements/CheckoutPage.tsx
> +	const [clientSecret, setClientSecret] = useState<string | undefined>(
dans les 2 cas tu initialise ton state à undefined, vu que tu le type en string | undefined, laisse vide ton state, il sera forcement undefined

2024-10-07 12:57 UTC, ThomMarchand commented on frontend/src/pages/premium/index.tsx
> +							{/* {option.external && <ExternalLinkIcon className="h-4 w-4 ml-2" />} */}
a delete

2024-10-07 12:57 UTC, ThomMarchand commented on frontend/src/pages/premium/index.tsx
> +										// onClick={unsubscribe}
delete commentaire

2024-10-09 06:59 UTC, ThomMarchand approved these changes

2024-10-09 07:02 UTC, merged