integrate project's isPublic status change
WildCodeSchool/2023-11-wns-bleu-g1 pull request #170
Opened 2024-08-30 14:01 UTC by zNeosx

2024-08-30 19:12 UTC, Pouish85 commented
Quand tu change de public à privé ou inversement et que tu enregistre, tu reviens sur ta page de profil, le statut du projet n'a pas bougé. un petit refetch?

2024-08-30 19:32 UTC, Pouish85 requested changes
Le petit problème de refetch, sinon le reste c'est du style

2024-08-30 19:32 UTC, Pouish85 commented on frontend/src/pages/coding/[id].tsx
> +							</Button>
```suggestion
							<Button
								size={"sm"}
								className="gap-2"
								onClick={saveCode}
								variant={"dark"}
							>
								<Save />
								Enregistrer
							</Button>
```
Quand le variant dark sera disponible, je trouve que ça colle mieux aux couleurs du site que le bleu
![image](https://github.com/user-attachments/assets/269c1426-4bba-46d3-81f1-e20fb26256fd)

2024-08-30 19:32 UTC, Pouish85 commented on frontend/src/pages/coding/[id].tsx
> +							<div className="flex items-center space-x-2">
```suggestion
						<div className="flex items-center self-end md:self-center gap-5">
								<LikeButton project={project} userId={userId} />
								<div className="flex items-center space-x-2">
```
C'est dommage de mettre le bouton de like en bas, il est invisible, ne serait-il pas mieux vers là?
![image](https://github.com/user-attachments/assets/319cb487-40d9-4b73-bfdd-9a3d3a3594bc)

2024-08-30 19:35 UTC, zNeosx commented on frontend/src/pages/coding/[id].tsx
> +							<div className="flex items-center space-x-2">
Yes mais vu qu'il y aura les commentaires en bas à voir ce que ça donne par la suite, je me suis inspiré d'i*Instagram (avec j'aime, commentaires et partage), on demandera aux autres ce qu'ils en pensent

2024-08-30 19:36 UTC, zNeosx commented on frontend/src/pages/coding/[id].tsx
> +							</Button>
Okok ben je testerai ça avec le variant dark, mais oui sur le screen c'est pas mal

2024-08-30 19:38 UTC, zNeosx commented
> Quand tu change de public à privé ou inversement et que tu enregistre, tu reviens sur ta page de profil, le statut du projet n'a pas bougé. un petit refetch?

Yes merci, je rajouterai le refetch pour les projets persos 😁

2024-08-30 20:02 UTC, Pouish85 commented on frontend/src/pages/coding/[id].tsx
> +							<div className="flex items-center space-x-2">
ha oui pas pensé au commentaires, a voir plus tard alors ;)

2024-10-02 14:17 UTC, Pouish85 approved these changes

2024-10-02 14:17 UTC, merged